version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
